### ISSUE TITLE
[docs] .mdx files should be under src/docs/, not src/docs/images/

### ISSUE THREAD

**Issue by jankeromnes** [nisarhassan12/theia-site#2]
All documentation `.mdx` files are currently under [src/docs/images/](https://github.com/nisarhassan12/theia-site/tree/master/src/docs/images). Since they're not actually images, they should be under [src/docs/](https://github.com/nisarhassan12/theia-site/tree/master/src/docs) instead.

Also, you mentioned some markdown errors in the Preferences page. I didn't see any markdown errors, but then again the page is [almost empty](https://github.com/nisarhassan12/theia-site/blob/1d7632a9d9b3237c0b8bb0c87966092207a11cd7/src/docs/images/Preferences.mdx). Maybe you forgot to commit some markdown content there?

**Comment by nisarhassan12** [comment]
Thanks! It's empty intentionally I removed this to make sure that the error is coming from the markdown there if you copy/paste this from https://github.com/theia-ide/theia-website/blob/master/doc/Preferences.md You will get the errors.

**Comment by nisarhassan12** [comment]
@jankeromnes  Thanks! It's empty intentionally I removed this to make sure that the error is coming from the markdown in the preferences.mdx if you copy/paste this from https://github.com/theia-ide/theia-website/blob/master/doc/Preferences.md  into the file you will get the errors. I forgot to add the markdown that was removed for debugging.
