### ISSUE TITLE
Slightly increase space between Ericsson and SAP logos

### ISSUE THREAD

**Issue by jankeromnes** [nisarhassan12/theia-site#7]
The contributor logos look spaced quite homogeneously, except SAP seems very close to Ericsson:

<img width="1214" alt="Screenshot 2019-08-21 at 09 01 21" src="https://user-images.githubusercontent.com/599268/63409873-4e058f80-c3f2-11e9-8633-8ec038dfd65e.png">

Maybe increase space between the two just a little? Not super important though.

**Comment by nisarhassan12** [comment]
Thanks!
